config/routes.rb
AirDolphinsBot::Application.routes.draw do
  match "/profile/edit" => "profiles#edit", as: :edit_profile
  put "/profile" => "profiles#update", as: :update_profile
  get "/profile" => "profiles#show", as: :profile

  resources :schedules

  post "/tweet" => "schedules#tweet", as: :tweet

  root to: "index#index", as: :index

  post "/update" => "index#update", as: :update

  post "/reply" => "index#reply", as: :reply

  match "/auth/:provider/callback" => "sessions#callback"
  match "/logout" => "sessions#destroy", :as => :logout

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  attr_accessible :birthday, :etc, :mail, :name, :number, :position, :uid
  validates :name, presence: true
  def self.create(user_id, name, uid)
    create! do |profile|
      profile.name = name
      profile.uid = uid
      profile.user_id = user_id
    end
  end
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  attr_accessible :action, :date, :location

  class << self
    def create(param)
      create! do |schedule|
        schedule.location = param[:location]
        schedule.action = param[:action]
        schedule.date = param[:date]
      end
    end

    def edit(id)
      base = Schedule.find(id)
      date = base[:date]
      base[:date] = Time.new(date.slice(0..4), date.slice(5..7), date.slice(8..10), date.slice(14..16), date.slice(17..19))
      base
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :provider, :screen_name, :uid
  has_one :profile, foreign_key: :user_id, primary_key: :id

  class << self
    def create_with_omniauth(auth)
      create! do |user|
        user.provider = auth["provider"]
        user.uid = auth["uid"]
        user.name = auth["info"]["name"]
        user.screen_name = auth["info"]["nickname"]
      end
    end

    def find_user(provider, uid)
      find_by_provider_and_uid(provider, uid)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Jpmobile::ViewSelector
  protect_from_forgery

  private
  def self.consumer
    OAuth::Consumer.new(
      ENV['CONSUMER_KEY'],
      ENV['CONSUMER_SECRET'],
      {site: "http://api.twitter.com"}
    )
  end

  protected
  def self.token
    OAuth::AccessToken.new(
      consumer,
      ENV['ACCESS_TOKEN'],
      ENV['ACCESS_TOKEN_SECRET']
    )
  end

  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/index_controller.rb
# encoding: utf-8
class IndexController < ApplicationController
  def index

    rubytter = OAuthRubytter.new(self.class.token)
    @tweets = rubytter.friends_timeline
    @members = Profile.order("number")

  end

  def update

    tweet = params[:tweet]

    rubytter = OAuthRubytter.new(self.class.token)
    rubytter.update("#{tweet} (tweet by #{current_user.screen_name} #{Time.now.strftime("at %H:%M:%S") })")

    redirect_to :index
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @profile = current_user.profile

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @profile }
    end
  end

  # GET /profiles/1/edit
  def edit
    @profile = current_user.profile
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(params[:profile])

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render json: @profile, status: :created, location: @profile }
      else
        format.html { render action: "new" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /profiles/1
  # PUT /profiles/1.json
  def update
    @profile = current_user.profile

    respond_to do |format|
      if @profile.update_attributes(params[:profile])
        format.html { redirect_to :profile, notice: 'Profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/schedules_controller.rb
# encoding: utf-8
class SchedulesController < ApplicationController
  # GET /schedules
  # GET /schedules.json
  def index
    today = Date.today
    now = today.to_s.slice(4..7)
    @schedules = Schedule.order("date").where("date like ?", "%#{now}%")

    coming = today.next_month.to_s.slice(4..7)
    @next_schedules = Schedule.order("date").where("date like ?", "%#{coming}%")

    rubytter = OAuthRubytter.new(self.class.token)
    @timeline = rubytter.user_timeline("781825164", {"count" => 10})

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @schedules }
    end
  end

  def tweet

    date = params[:date]
    site = params[:location]
    rubytter = OAuthRubytter.new(self.class.token)
    rubytter.update("日時: #{date} \n場所: #{site} #練習日\n(#{Time.now.strftime("at %H:%M:%S") })")

    redirect_to :schedules
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
    @schedule = Schedule.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @schedule }
    end
  end

  # GET /schedules/new
  # GET /schedules/new.json
  def new
    @schedule = Schedule.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @schedule }
    end
  end

  # GET /schedules/1/edit
  def edit
    @schedule = Schedule.edit(params[:id])
  end

  def format(param)
    week = ["日", "月", "火", "水", "木", "金", "土"]

    schedule = params[:schedule]
    day = Date::new(schedule["date(1i)"].to_i, schedule["date(2i)"].to_i, schedule["date(3i)"].to_i)
    time = "#{params[:schedule]["date(4i)"]}:#{params[:schedule]["date(5i)"]}"
    date = "#{day.to_s}(#{week[day.wday]}) #{time}"

    if schedule[:location].blank?
      schedule[:location] = "未定"
    end

    pram = {date: date, location: schedule[:location], action: schedule[:action]}
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.create(format(params))

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render json: @schedule, status: :created, location: @schedule }
      else
        format.html { render action: "new" }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /schedules/1
  # PUT /schedules/1.json
  def update
    @schedule = Schedule.find(params[:id])

    respond_to do |format|
      if @schedule.update_attributes(format(params))
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy

    respond_to do |format|
      format.html { redirect_to schedules_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def callback
    auth = request.env["omniauth.auth"]
    user = User.find_user(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id

    profile = user.profile || Profile.create(user.id, user.name, user.uid)
    redirect_to :profile
  end

  def destroy
    session[:user_id] = nil
    redirect_to :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/index/index.html.erb
<% if !request.smart_phone? %>
  <div id="tweet_update">
    <%= form_tag(:controller=>"index", :action=>"update") do %>
      <%= text_field_tag "tweet" %>
      <%= submit_tag("ツイートする") %>
    <% end %>
  </div>
<% end %>
<div id="members">
  <fieldset>
    <legend>メンバーリスト</legend>
      <table>
      <% @members.each do |member| %>
        <tr>
          <td class="no">No.<%= member.number %></td>
          <td class="position"><%= member.position %></td>
          <td class="name"><%= member.name %></td>
        </tr>
      <% end %>
      </table>
  </fieldset>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AirDolphinsBot</title>
<% if !request.smart_phone? %>
  <%= stylesheet_link_tag    "application" %>
<% else %>
  <%= stylesheet_link_tag    "smart_phone/application" %>
<% end %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if request.smart_phone? %>
  <p id="team">AirDolphins</p>
<% else %>
  <span id="team">AirDolphins</span>
<% end %>
<% if current_user %>
  <span class="logout">Hello <%= current_user.name %> @<%= current_user.screen_name %> <%= link_to 'ログアウト', logout_path %></span>
  <div id="main">
    <p class="link"><%= link_to 'Top', index_path %> / <%= link_to 'Schedule', schedules_path %> / <%= link_to 'My Profile', profile_path %></p>
    <%= yield %>
  </div>
<% else %>
  <div class="login"><span><%= link_to 'Twitterでログイン', '/auth/twitter' %></span></div>
<% end %>
</body>
</html>

app/views/profiles/_form.html.erb
<%= form_for @profile, as: :profile, url: profile_path(), method: :put do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>* 必須<br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :number %> - 希望でもいいよ<br />
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :position %><br />
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :mail %> - いつかメール出します<br />
    <%= f.text_field :mail %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br />
    <%= f.date_select :birthday, :start_year => 1988, :end_year => Time.now.year-15, :use_month_numbers => true %>
  </div>
  <div class="field">
    <%= f.label :etc %><br />
    <%= f.text_area :etc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form' %>

app/views/profiles/index.html.erb
<h1>Listing profiles</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Number</th>
    <th>Position</th>
    <th>Uid</th>
    <th>Mail</th>
    <th>Birthday</th>
    <th>Etc</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @profiles.each do |profile| %>
  <tr>
    <td><%= profile.name %></td>
    <td><%= profile.number %></td>
    <td><%= profile.position %></td>
    <td><%= profile.uid %></td>
    <td><%= profile.mail %></td>
    <td><%= profile.birthday %></td>
    <td><%= profile.etc %></td>
    <td><%= link_to 'Show', profile %></td>
    <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
    <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<div id="my_view">
  <fieldset>
    <legend>プロフィール</legend>
<p>
  <b>Name:</b>
  <%= @profile.name %>
</p>

<p>
  <b>Number:</b>
  <%= @profile.number %>
</p>

<p>
  <b>Position:</b>
  <%= @profile.position %>
</p>

<p>
  <b>Mail:</b>
  <%= @profile.mail %>
</p>

<p>
  <b>Birthday:</b>
  <%= @profile.birthday %>
</p>

<p>
  <b>Etc:</b>
  <%= @profile.etc %>
</p>
</div>

<div id="edit_link">
<%= link_to 'Edit', edit_profile_path(@profile) %>
</div>

app/views/schedules/_form.html.erb
<%= form_for(@schedule) do |f| %>
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% @schedule.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date,
                          :default => {:month => Time.now.month, :day => 1, :hour => 18, :min => 30},
                          :start_year => Time.now.year,
                          :use_month_numbers => true,
                          :minute_step => 30
    %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_area :location, :value => "神奈川中学校"%>
  </div>
  <div class="field">
    <%= f.label :action %><br />
    <%= f.select :action, [["練習", 1],["試合", 2]] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<h1>Editing schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<h1>予定一覧</h1>

<div id="schedule_list">
<fieldset>
  <legend>今月</legend>
<% @schedules.each do |schedule| %>
  <div class="one_day">
    <div>
      <%= form_tag(:controller=>"schedules", :action=>"tweet") do %>
        <%= hidden_field_tag(:date, schedule.date) %>
        <%= hidden_field_tag(:location, schedule.location) %>
        <%= submit_tag("tweet") %>
      <% end %>
    </div>
    <p>日付: <strong><%= schedule.date %></strong></p>
    <p>場所: <strong><%= schedule.location %></strong></p>
    <p>
      <span><%= link_to 'Show', schedule %></span>
      <span><%= link_to 'Edit', edit_schedule_path(schedule) %></span>
      <% if !request.smart_phone? %>
        <span><%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' } %></span>
      <% end %>
    </p>
  </div>
<% end %>
</fieldset>

<fieldset>
  <legend>翌月</legend>
<% @next_schedules.each do |schedule| %>
  <div class="one_day">
    <div>
      <%= form_tag(:controller=>"schedules", :action=>"tweet") do %>
        <%= hidden_field_tag(:date, schedule.date) %>
        <%= hidden_field_tag(:location, schedule.location) %>
        <%= submit_tag("tweet") %>
      <% end %>
    </div>
    <p>日付: <%= schedule.date %></p>
    <p>場所: <%= schedule.location %></p>
    <p>
      <span><%= link_to 'Show', schedule %></span>
      <span><%= link_to 'Edit', edit_schedule_path(schedule) %></span>
      <% if !request.smart_phone? %>
        <span><%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' } %></span>
      <% end %>
    </p>
  </div>
<% end %>
</fieldset>
<p><%= link_to 'New Schedule', new_schedule_path %></p>
</div>

<% if !request.smart_phone? %>
<div id="timeline">
  <dl>
    <% @timeline.each do |t| %>
    <dt><%= image_tag t.user.profile_image_url, size: '40x40' %></dt>
    <dd><%= t.user.name %></dd>
    <dd><%= t.text %></dd>
    <% end %>
  </dl>
<br />
</div>
<% end %>

app/views/schedules/new.html.erb
<h1>New schedule</h1>

<%= render 'form' %>

<%= link_to 'Back', schedules_path %>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @schedule.date %>
</p>

<p>
  <b>Location:</b>
  <%= @schedule.location %>
</p>

<p>
  <b>Action:</b>
  <%= @schedule.action %>
</p>


<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>